export const currencyMap = [
    { currency: "USD", label: "United States Dollar" },
    { currency: "JPY", label: "Japanese Yen" },
    { currency: "BGN", label: "Bulgarian Lev" },
    { currency: "CZK", label: "Czech Koruna" },
    { currency: "DKK", label: "Danish Krone" },
    { currency: "GBP", label: "Pound Sterling" },
    { currency: "HUF", label: "Hungarian Forint" },
    { currency: "PLN", label: "Polish Złoty" },
    { currency: "RON", label: "Romanian Leu" },
    { currency: "SEK", label: "Swedish Krona" },
    { currency: "CHF", label: "Swiss Franc" },
    { currency: "ISK", label: "Icelandic Króna" },
    { currency: "NOK", label: "Norwegian Krone" },
    { currency: "TRY", label: "Turkish Lira" },
    { currency: "AUD", label: "Australian Dollar" },
    { currency: "BRL", label: "Brazilian Real" },
    { currency: "CAD", label: "Canadian Dollar" },
    { currency: "CNY", label: "Chinese Yuan" },
    { currency: "HKD", label: "Hong Kong Dollar" },
    { currency: "IDR", label: "Indonesian Rupiah" },
    { currency: "ILS", label: "Israeli New Shekel" },
    { currency: "INR", label: "Indian Rupee" },
    { currency: "KRW", label: "South Korean Won" },
    { currency: "MXN", label: "Mexican Peso" },
    { currency: "MYR", label: "Malaysian Ringgit" },
    { currency: "NZD", label: "New Zealand Dollar" },
    { currency: "PHP", label: "Philippine Peso" },
    { currency: "SGD", label: "Singapore Dollar" },
    { currency: "THB", label: "Thai Baht" },
    { currency: "ZAR", label: "South African Rand" },
];
